# Generated by Django 4.2.7 on 2025-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTvshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('videoUrl', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='PopularMovie',
        ),
        migrations.RenameField(
            model_name='popularmovie',
            old_name='videUrl',
            new_name='videoUrl',
        ),
    ]
