# Generated by Django 4.2.7 on 2025-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularmovie',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers')], max_length=255),
        ),
        migrations.AlterField(
            model_name='populartvshow',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers')], max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers')], max_length=255),
        ),
    ]
