# Generated by Django 4.2.7 on 2025-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0005_alter_popularmovie_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularMovie',
        ),
        migrations.DeleteModel(
            name='PopularTvshow',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies')], max_length=255),
        ),
    ]
