# Generated by Django 4.2.7 on 2025-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_delete_popularmovie_delete_populartvshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
