# Generated by Django 4.2.7 on 2025-10-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0007_video_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('videoUrl', models.TextField()),
                ('details', models.TextField(default='')),
                ('email', models.TextField()),
            ],
        ),
    ]
