# Generated by Django 4.2.7 on 2025-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0009_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='videoUrl',
            field=models.TextField(default=''),
        ),
    ]
