# Generated by Django 4.2.7 on 2025-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0010_wallpaper_image_wallpaper_videourl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallpaper',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers')], max_length=255),
        ),
    ]
