# Generated by Django 4.2.7 on 2026-01-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0011_delete_wallpaper_alter_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers')], max_length=255)),
                ('image', models.TextField()),
                ('videoUrl', models.TextField()),
                ('details', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers')], max_length=255)),
                ('image', models.TextField()),
                ('videoUrl', models.TextField()),
                ('details', models.TextField(default='')),
            ],
        ),
    ]
