# Generated by Django 4.2.7 on 2026-04-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0012_movie_tvshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers'), ('act_tvshow', 'Action_TvShows'), ('drm_tvshow', 'Drama_TvShows'), ('cmd_tvshow', 'Comedy_TvShows'), ('hor_tvshow', 'Horror_TvShows'), ('rom_tvshow', 'Romance_TvShows'), ('sci_tvshow', 'Sci-fi_TvShows'), ('doc_tvshow', 'Documentary_TvShows'), ('thr_tvshow', 'Thrillers_TvShows')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers'), ('act_tvshow', 'Action_TvShows'), ('drm_tvshow', 'Drama_TvShows'), ('cmd_tvshow', 'Comedy_TvShows'), ('hor_tvshow', 'Horror_TvShows'), ('rom_tvshow', 'Romance_TvShows'), ('sci_tvshow', 'Sci-fi_TvShows'), ('doc_tvshow', 'Documentary_TvShows'), ('thr_tvshow', 'Thrillers_TvShows')], max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(choices=[('act', 'Action'), ('drm', 'Drama'), ('cmd', 'Comedy'), ('hor', 'Horror'), ('rom', 'Romance'), ('sci', 'Sci-fi'), ('doc', 'Documentary'), ('thr', 'Thrillers'), ('pop', 'popular Tv Shows'), ('mov', 'popular Movies'), ('wall', 'Wallpapers'), ('act_tvshow', 'Action_TvShows'), ('drm_tvshow', 'Drama_TvShows'), ('cmd_tvshow', 'Comedy_TvShows'), ('hor_tvshow', 'Horror_TvShows'), ('rom_tvshow', 'Romance_TvShows'), ('sci_tvshow', 'Sci-fi_TvShows'), ('doc_tvshow', 'Documentary_TvShows'), ('thr_tvshow', 'Thrillers_TvShows')], max_length=255),
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videoapp.video')),
            ],
            options={
                'unique_together': {('video', 'email')},
            },
        ),
    ]
