# Generated by Django 4.2.7 on 2026-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0013_alter_movie_description_alter_tvshow_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='count_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='count_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
