# Generated by Django 4.2.7 on 2026-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0014_movie_count_likes_tvshow_count_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254),
        ),
    ]
